defaults:
  - _self_  # all below configs will override this conf.yaml

seed: 42

exp_root_dir: "./exp"
exp_name:

dataset:
  task: "classification"
  root: "./data/${dataset.task}"
  img_dim: 2
  mri_type: "T1wCE"
  split:
    root: "./train_val_splits"
    seed: 42
    ratio: 0.1
  input_size:
    - 64
    - 64
  aug:
      rot_factor: 10 # rotation degree range in [0, 180] 
      rot_p: 0.25 # rotation probability
      scale_factor: 0.1 # scale factor
      h_flip_p: 0.1
  max_slice_num: 128 # only for 2.5d mode

model:
  type: resnet_50_2d
  pretrained: ""
  args:
    num_classes: 2
  mlp_input_dim: 256 # for 2.5d mode
  mlp_args: # only for 2.5d mode
    input_dim: ${model.mlp_input_dim}
    hidden_dim: 128
    output_dim: 2
    hidden_depth: 4

loss:
  task: ${dataset.task}
  args:
    reduction: "mean"
  
train:
  batch_size: 128
  num_workers: 32
  lr: 1e-3
  weight_decay: 1e-6
  max_epochs: 200
  devices: 4
  strategy: "ddp"
  scheduler:
    lr_cosine_min: 1e-6
    lr_cosine_epochs: ${train.max_epochs}
    lr_cosine_warmup_epochs: 0

checkpoint:
  monitor: "val_acc"
  mode: "max"
  save_last: true
  save_top_k: 1
  filename: "{epoch:02d}-{val_acc:.4f}"

hydra:
  run:
    dir: .
  output_subdir: null