defaults:
  - _self_  # all below configs will override this conf.yaml

seed: 42

exp_root_dir: "./exp"
exp_name:

dataset:
  task: "classification"
  root: "./data/${dataset.task}"
  img_dim: 2
  mri_type: "T1wCE"
  split:
    root: "./train_val_splits"
    seed: 42
    ratio: 0.1
  input_size:
    - 128
    - 128
  aug:
      rot_factor: 40
      rot_p: 0.6
      scale_factor: 0.3

model:
  type: resnet_50_2d
  pretrained: ""
  args:
    num_classes: 2

loss:
  task: ${dataset.task}
  args:
    reduction: "mean"
  
train:
  batch_size: 32
  num_workers: 1
  lr: 1e-3
  weight_decay: 1e-2
  max_epochs: 100
  devices: 1
  strategy: "ddp"
  scheduler:
    lr_cosine_min: 1e-5
    lr_cosine_epochs: ${train.max_epochs}
    lr_cosine_warmup_epochs: 5

checkpoint:
  monitor: "val_acc"
  mode: "max"
  save_last: true
  save_top_k: 5
  filename: "{epoch:02d}-{val_acc:.4f}"

hydra:
  run:
    dir: .
  output_subdir: null