meta_data:
  pipeline_exp_name: "benchmark"
  description: "training snn"
  num_workers: 1
  use_gpu: true
  key_config:
    common:
      model_name: "model"
    algo_training:
      lr: :lr

common:
  model_name: 'SpikingNeuralNetwork'
  seed: 42

  task: "classification"
  root: "./data/classification"
  img_dim: 2
  mri_type: "T1wCE"
  split:
    root: "./train_val_splits"
    seed: 42
    ratio: 0.1
  input_size:
    - 36
    - 36
  aug:
      rot_factor: 10 # rotation degree range in [0, 180] 
      rot_p: 0.25 # rotation probability
      scale_factor: 0.1 # scale factor
      h_flip_p: 0.1
  max_slice_num: 128 # only for 2.5d mode

algo_training:
  variables:
    batch_size: [128]
    lr: [0.001]
    max_epochs: [80]
    num_steps: [128]
    val_num_steps: [128]

  constants:
    exp_name: "csnn_train"  # exp_name is required
    script_path: brain_tumor/learn/snn_trainer.py
    num_classes: 2
    mlp_input_dim: 256 # for 2.5d mode
    mlp_args: # only for 2.5d mode
      input_dim: 256
      hidden_dim: 128
      output_dim: 2
      hidden_depth: 2
  

