defaults:
  - _self_  # all below configs will override this conf.yaml

seed: 42
use_gpu: true
gpu: 1

exp_root_dir: "./exp"
exp_name:
experiment: "configs/snn.yaml"

dataset:
  task: "classification"
  root: "./data/${dataset.task}"
  img_dim: 2
  mri_type: "T1wCE"
  split:
    root: "./train_val_splits"
    seed: 42
    ratio: 0.1
  input_size:
    - 128
    - 128
  aug:
      rot_factor: 40 # rotation degree range in [0, 180] 
      rot_p: 0.4 # rotation probability
      scale_factor: 0.3 # scale factor
      h_flip_p: 0.5
  max_slice_num: 128 # only for 2.5d mode

model:
  type: SpikingNeuralNetwork
  pretrained: ""
  args:
    num_classes: 2
  mlp_input_dim: 256 # for 2.5d mode
  mlp_args: # only for 2.5d mode
    input_dim: ${model.mlp_input_dim}
    hidden_dim: 128
    output_dim: 2
    hidden_depth: 2

loss:
  model_name: "snn"
  task: ${dataset.task}
  args:
    reduction: "mean"
  
train:
  batch_size: 32
  num_workers: 8
  lr: 1e-4
  weight_decay: 1e-2
  max_epochs: 100
  num_steps: 10
  val_num_steps: 1
  devices: 1
  strategy: "ddp"
  scheduler:
    lr_cosine_min: 1e-6
    lr_cosine_epochs: ${train.max_epochs}
    lr_cosine_warmup_epochs: 0

checkpoint:
  monitor: "val_acc"
  mode: "max"
  save_last: true
  save_top_k: 3
  filename: "{epoch:02d}-{val_acc:.4f}"

hydra:
  run:
    dir: .
  output_subdir: null